# Generated by Django 4.0.4 on 2022-06-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_comment_author_alter_comment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
