# Generated by Django 4.0.4 on 2022-07-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='autor',
            new_name='author',
        ),
    ]
